# Aggregations: Min, Max and Multidimentional Aggregate

In [1]:
import numpy as np

In [2]:
L = np.random.random(100)
sum(L)

53.568873354518594

In [3]:
np.sum(L)

53.56887335451862

In [4]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

323 ms ± 48.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.85 ms ± 92.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Minimum and Maximum

In [5]:
min(big_array), max(big_array)

(3.813287969833823e-07, 0.9999992605503593)

In [6]:
np.min(big_array), np.max(big_array)

(3.813287969833823e-07, 0.9999992605503593)

In [7]:
%timeit min(big_array)
%timeit np.min(big_array)

195 ms ± 5.79 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
981 µs ± 86.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
print(big_array.min(), big_array.max(), big_array.sum())

3.813287969833823e-07 0.9999992605503593 499925.7172128223


# Multi dimensional aggregates

In [9]:
M = np.random.random((3, 4))
print(M)

[[0.33368396 0.77164748 0.47950864 0.98520977]
 [0.66054591 0.53112733 0.543611   0.00722197]
 [0.19417772 0.79703648 0.92001815 0.18443526]]


In [10]:
M.sum()

6.408223683196102

In [11]:
M.min(axis=0)

array([0.19417772, 0.53112733, 0.47950864, 0.00722197])

In [12]:
M.max(axis=1)

array([0.98520977, 0.66054591, 0.92001815])